[tool.poetry]
name = "gistapi"
version = "0.1.0"
description = "A simple HTTP API server for searching user's GitHub Gists."
authors = ["Asim"]

[tool.poetry.dependencies]
python = "^3.10"
Flask = "2.2.2"
Werkzeug = "^2.0.0" 
requests = "2.28.1"
pydantic = "1.9.0"
aiohttp = "3.8.1"
gunicorn = "^20.1.0"
uvicorn = {version = "^0.17.6", extras = ["standard"]}
asgiref = "^3.7.2"
pytest = "7.4.3"

[tool.poetry.group.dev.dependencies]
black = "^23.10.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
