[tool.poetry]
name = "backend-coding-challenge"
version = "0.1.0"
description = "Coding challenge"
authors = ["Ivan Spasojević <spasojevic.ivan@gmail.com>"]
readme = "README.md"
packages = [{include = "backend_coding_challenge"}]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.2.2"
Flask-RESTful = "^0.3.9"
black = "^22.10.0"
pytest = "^7.1.3"
uvicorn = "^0.18.3"
requests = "^2.28.1"
gunicorn = "^20.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
