[tool.poetry]
name = "gistapi"
version = "0.1.0"
description = "simply gist api"
authors = ["Caleb Carvalho"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.1"
Flask = "^2.2.2"
Flask-Limiter = "^2.6.2"
pydantic = "^1.10.2"


[tool.poetry.group.dev.dependencies]
isort = "^5.10.1"
pytest = "^7.1.3"
black = "^22.8.0"
flake8 = "^5.0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
serve = "gistapi:main"
